# ----------------------- AudioConnect ----------------------- #
#                                                              #
#      Author: Weasel_Squeezer                                 #
#      Website: minecraftaudio.com                             #
#                                                              #
# ------------------------------------------------------------ #

# NOTICE:
#  For more information and a step-by-step guide on how to setup
#  and configure AudioConnect, refer to the quick and easy tutorial
#  here (https://minecraftaudio.com/tutorial)

connection:
  # The user-id of your AudioConnect account (Minecraft UUID/Username)
  user-id: ''

  # The password of your AudioConnect account (Chosen when creating an account)
  user-password: ''

  # The ID for this server (Generated for each server added to your account)
  server-id: ''

  # NOTICE: These values will most likely never need to be changed and probably shouln't (depending on use case)
  endpoint:
    # WARNING: If this is false, your user credentials will be transmitted in plain text
    # The boolean flag indicating whether to use an SSL (secure) connection with the AudioConnect webserver endpoint
    # If true (websocket protocol = wss, web protocol = https). If false: (websocket protocol = ws, web protocol = http)
    secure: true
    # The host of the AudioConnect webserver
    host: minecraftaudio.com
    # The port of the AudioConnect websocket endpoint
    websocket-port: 3030
    # The port of the AudioConnect webapp endpoint
    webapp-port: 80
    # The path of the AudioConnect webapp endpoint
    webapp-path: /

# Configure settings for reconnecting to the AudioConnect server in the event of an unexpected disconnect.
# If the reason for the disconnect was because the server refused the conneciton, or if the client was manually
# disconnected, the client will not attempt to reconnect.
reconnect:
  # The number of miliseconds to delay before attempting to reconnect
  interval: 3000
  # The maximum number of milliseconds to delay a reconnect attempt
  max-interval: 30000
  # The rate of increase of the reconnect delay. Allows reconnect attempts to back off when problems persist
  delay: 1.2
  # The maximum number of reconnect attempts that will be made before giving up. 
  # If -1, reconnect attempts will continue to be made forever.
  max-attempts: -1

options:
  # prevent a player from executing any AudioConnect command after this amount of time in seconds from the last executed command
  command-cooldown: 5
  # The frequency (in seconds) of audio connect announcement with connection URL for non-connected players. -1 for no announcements
  announce-frequency: 2700

# Define audio tracks and their settings to allow different audio types to be played independently from each other.
audio-tracks:
  primary:
    default: true
    repeating: true
    random: true
    fading: true
  background:
    repeating: true
    random: true
    fading: false
  complementary:
    repeating: false
    random: false
    fading: false
# <track-name>
#   default: <true|false>
#   repeating: <true|false>
#   random: <true|false>
#   fading: <true|false>
