name: AudioConnect
main: com.deadmandungeons.audioconnect.AudioConnect
version: 1.2.4
author: Weasel_Squeezer
website: https://minecraftaudio.com

depend: [DeadmanPlugin, WorldGuard]

commands:
    ac:
        description: AudioConnect command prefix. Use "/ac help" to see all the AudioConnect commands you can use.
    audio:
        aliases: [music]
        description: Alias for /ac connect
    mute:
        description: Alias for /ac mute
    unmute:
        description: Alias for /ac unmute

permissions:
    audioconnect.*:
        default: op
        description: Gieves access to all AudioConnect permissions
        children:
            audioconnect.all: true
    audioconnect.all:
        default: op
        description: Gives access to all AudioConnect permissions
        children:
            audioconnect.admin.all: true
            audioconnect.user.all: true
    audioconnect.admin.*:
        default: op
        description: Gives access to all AudioConnect admin permissions
        children:
            audioconnect.admin.all: true
    audioconnect.admin.all:
        default: op
        description: Gives access to all AudioConnect setup permissions
        children:
            audioconnect.admin.register: true
            audioconnect.admin.reload: true
            audioconnect.admin.list: true
            audioconnect.admin.send: true
    audioconnect.admin.register:
        description: Gives access to initiate the registration of the server with an AudioConnect account
    audioconnect.admin.reload:
        description: Gives access to reload this plugin and reconnect
    audioconnect.admin.list:
        description: Gives access to list the connected players and available audio
    audioconnect.admin.send:
        description: Gives access to send and play audio to a connected player
    audioconnect.user.*:
        default: true
        description: Gives access to all AudioConnect user permissions
        children:
            audioconnect.user.all: true
    audioconnect.user.all:
        default: true
        description: Gives access to all AudioConnect user permissions
        children:
            audioconnect.user.register: true
            audioconnect.user.connect: true
    audioconnect.user.register:
        description: Gives access to initiate the registration of an AudioConnect account
    audioconnect.user.connect:
        description: Gives access to retrieve connection URL
