name: AudioConnect
main: com.deadmandungeons.audioconnect.AudioConnect
version: 1.0.4
author: Weasel_Squeezer
website: http://www.deadmandungeons.com

depend: [DeadmanPlugin, WorldGuard]

commands:
    ac:
        description: AudioConnect command prefix. Use "/ac help" to see all the AudioConnect commands you can use.
    music:
        description: Alias for /ac connect
    mute:
        description: Alias for /ac mute
    unmute:
        description: Alias for /ac unmute

permissions:
    audioconnect.*:
        default: op
        description: Gieves access to all AudioConnect permissions
        children:
            audioconnect.all: true
    audioconnect.all:
        default: op
        description: Gives access to all AudioConnect permissions
        children:
            audioconnect.admin.all: true
            audioconnect.user.all: true
    audioconnect.admin.*:
        default: op
        description: Gives access to all AudioConnect admin permissions
        children:
            audioconnect.admin.all: true
    audioconnect.admin.all:
        default: op
        description: Gives access to all AudioConnect setup permissions
        children:
            audioconnect.admin.reload: true
            audioconnect.admin.list: true
            audioconnect.admin.send: true
    audioconnect.user.*:
        default: true
        description: Gives access to all AudioConnect user permissions
        children:
            audioconnect.user.all: true
    audioconnect.user.all:
        default: true
        description: Gives access to all AudioConnect user permissions
        children:
            audioconnect.user.connect: true